### ISSUE TITLE
HTML tags in titles

### ISSUE THREAD

**Issue by zerosonesfun** [akirk/friends#123]
This may be something wrong with my WordPress installation or a plugin issue. I have HTML tags in the titles in my friends feed.

<img width="928" alt="Screen Shot 2022-11-24 at 8 18 36 AM" src="https://user-images.githubusercontent.com/41351317/203794462-21abdb44-1e13-4bd0-95e8-dd92d8b49ab8.png">

Is this just my site?

Would there be a handy function I could paste in functions.php to strip?

**Comment by zerosonesfun** [comment]
I found the plugin. It's the microformats 2 indie web extension. It adds various classes like this. I suppose I'll be deactivating microformats since I'm not really sure how helpful microformats are these days anyway.

**Comment by akirk** [comment]
Hi @zerosonesfun, I'm not seeing this on my end. Could it be that you have a plugin that adds this?

**Comment by akirk** [comment]
Ah, that is good to know. I can take a look if I could ensure to deactivate it on the `/friends/` page now that I know which plugin it is.

**Comment by zerosonesfun** [comment]
> Ah, that is good to know. I can take a look if I could ensure to deactivate it on the `/friends/` page now that I know which plugin it is.

I'm now realizing that it won't help for me to deactivate it. If I'm friends with someone who uses this plugin, the html will be in their rss feed and therefore in my friends feed. At least, I think that's what's happening.

**Comment by zerosonesfun** [comment]
I re-opened this for a minute because I thought deactivating the microformats plugin didn't work. But, I failed to purge my cache. So, yes, it's definitely microformats. 🙂
