### ISSUE TITLE
Get old ActivityPub messages upon subscribe

### ISSUE THREAD

**Issue by akirk** [akirk/friends#136]
Eventhough Mastodon doesn't support backfill (see https://github.com/mastodon/mastodon/issues/34), we could fetch old messages by just querying the RSS feed of the Mastodon page once.

**Comment by zakwilson** [comment]
Reading the ActivityPub outbox also serves this purpose; there's no need to do it via RSS.

**Comment by akirk** [comment]
Thank you, I didn't know that. Need to explore this.

**Comment by akirk** [comment]
Thanks @zakwilson for the pointer, it works well!
