### ISSUE TITLE
User avatars are refering to `favicon.ico`

### ISSUE THREAD

**Issue by gbraad** [akirk/friends#139]
The avatars for the following accounts were not retrieved:

  * https://pixelfed.social/users/gbraad  
    Avatar URL: https://pixelfed.social/favicon.ico
    Server: Mastodon
  * https://social.gbraad.nl/profile/gbraad  
    Avatar URL: https://social.gbraad.nl/favicon.ico  
    Server: Friendica

is there a way to force this? Or is there something wrong with the retrieval?

**Comment by gbraad** [comment]
Not sure if this is part of the ActivityPub plugin from @pfefferle. But an `Actor` shoud have an `icon` refering to the user's profile picture. https://www.w3.org/TR/activitypub/#actor-objects

**Comment by gbraad** [comment]
^^^ According to this issue https://github.com/pfefferle/wordpress-activitypub/issues/211 it says gravatar should be used, but this is not the case.

**Comment by pfefferle** [comment]
The favicon is server related and not individual for every user, so the ActivityPlugin does not use it at all.

Can you explain the problem a bit more please? If the icon is missing when you follow your pixelfed instance using WordPress, it is friends related. If the comments from pixelfed are not showing an avatar in the WordPress comments section then it is an ActivityPub issue.

The ActivityPub issue you are referring to, is the other way around, that Pixelfed/Mastodon/... are not showing the correct avatar of a blog user.

**Comment by gbraad** [comment]
![Screenshot from 2022-12-29 20-14-14](https://user-images.githubusercontent.com/1894/209949782-0dc78017-7fac-4272-aef0-06ca3d1c0837.png)
![Screenshot from 2022-12-29 20-14-01](https://user-images.githubusercontent.com/1894/209949792-7c898291-640b-45d3-8698-8b20475f431e.png)

**Comment by pfefferle** [comment]
This is part of the friends plugin

**Comment by akirk** [comment]
The retrieval was not implemented. This was now done in #142.

**Comment by gbraad** [comment]
Thanks!

**Comment by gbraad** [comment]
@akirk After #143 it now loads, but clicking the button to set the avatar nothing happens. I see the page briefly 'blink' (reload) and the requested:

```
23.104.209.6 - - [30/Dec/2022:01:28:28 -0800] "GET /wp-admin/admin.php?page=edit-friend&user=5&wp_http_referer=%2Fwp-admin%2Fusers.php%3Frole%3Dfriend%2Cacquaintance%2Cfriend_request%2Cpending_friend_request%2Csubscription HTTP/2.0" 200 23953 "https://blog.gbraad.nl/wp-admin/admin.php?page=edit-friend&user=5&wp_http_referer=%2Fwp-admin%2Fusers.php%3Frole%3Dfriend%2Cacquaintance%2Cfriend_request%2Cpending_friend_request%2Csubscription" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

No error.

**Comment by akirk** [comment]
Could you try force reloading (or clear the cache)? I didn't set a cache buster yet.

**Comment by gbraad** [comment]
I am not aware I am using an additional cache; I removed WP Cache and deactivate Jetpack.

**Comment by akirk** [comment]
Sorry, I am talking about the browser cache. [I updated friends-admin.js](https://github.com/akirk/friends/pull/142/files#diff-d4fe49ae770b6d008ba08cc2fd347397dc07f84fd94feffec43870e9e40687c8) but your browser might still load the old version.

**Comment by gbraad** [comment]
Ah... I usually check using Private/Incognito. Have to admit, forgot that this time... checking again. Sorry
