### ISSUE TITLE
How to send a response to a status?

### ISSUE THREAD

**Issue by gbraad** [akirk/friends#144]
I can react to a status on the feed, like favourite, but I can seem to send a textual message?

![Screenshot from 2022-12-30 21-49-48](https://user-images.githubusercontent.com/1894/210077510-48cb7f5e-a0f3-4388-b907-036f36d18aad.png)

**Comment by HammyHavoc** [comment]
Ideally, this would integrate with the native WordPress comment system, and thus interactions would appear on the posts themselves in the front-end for anyone not browsing via ActivityPub.

**Comment by akirk** [comment]
Indeed, this is how I imagine this, too. If you comment on the post "locally", it should be posted as a note via ActivityPub.

Right now, that comments icon is only geared towards displaying comments via RSS but as recorded in #8 and somewhat #60, this should also display a comment form.

The ActivityPub plugin has an implementation of replies on ActivityPub should come in as comments already, so this will close that circle.

**Comment by mikewmerritt** [comment]
As a temporary solution on my own blog, I've added an icon that redirects to the new post screen. Because I also have Post Kinds installed, it will append the permalink of the comment to kindurl parameter and a kind=reply parameter.
