### ISSUE TITLE
Setting favourite on a status message is not communicated via ActivityPub

### ISSUE THREAD

**Issue by gbraad** [akirk/friends#145]
The following message was posted and a star was added:

![Screenshot from 2022-12-30 21-49-48](https://user-images.githubusercontent.com/1894/210077510-48cb7f5e-a0f3-4388-b907-036f36d18aad.png)

Ref: https://mastodon.social/@gbraad/109602761693174990/favourites

... but this was not set on the original post as can be seen (it should also have @gbraad@blog.gbraad.nl)

**Comment by akirk** [comment]
Unfortunately this is not yet implemented in ActivityPub but I am planning on doing so. The reactions are just cross-WordPress-Friends sites so far.

Let's keep this issue for tracking the ActivityPub implementation status.

**Comment by akirk** [comment]
This was fixed in #164.
