### ISSUE TITLE
If a favicon isn't set on a feed you follow, a broken image appears in `/friends` for the post

### ISSUE THREAD

**Issue by HammyHavoc** [akirk/friends#152]
See screenshot:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/503951/210191864-3939f502-c6a0-4a48-a864-de14eef23e16.png">

**Comment by gbraad** [comment]
Resolved as #139 in #142. Not in a released version yet

**Comment by akirk** [comment]
I think this is just via RSS, not ActivityPub. Can you confirm, @HammyHavoc?

**Comment by HammyHavoc** [comment]
Unfortunately, I've not been able to replicate the issue after adding a favicon and then removing one. I'm going to chalk it up to a Theme incompatibility issue on Bryan's site.

After removing the favicon, it now displays as what I would expect without a favicon:

<img width="247" alt="image" src="https://user-images.githubusercontent.com/503951/210214332-70ef952e-6537-40cf-a0a8-0d5eb753a0a2.png">

I'll let you know if I replicate it at a later point; setting up several sites with Friends plugins today, it's quite exciting!
