### ISSUE TITLE
Allow reading friends feeds in a feed reader

### ISSUE THREAD

**Issue by akirk** [akirk/friends#16]
We can do this by providing a download for a OPML file.

**Comment by akirk** [comment]
Implemented in 0.7

**Comment by chrisaldrich** [comment]
Replied to [Allow reading friends feeds in a feed reader · Issue #16 · akirk/friends](https://github.com/akirk/friends/issues/16) by [![Alex Kirk](https://avatars2.githubusercontent.com/u/203408?s=460&amp;v=4)Alex Kirk](https://github.com/akirk) _( GitHub)_

&gt; We can do this by providing a download for a OPML file.

Perhaps better than allowing simply the download of an OPML file, it would be nice to have the ability to provide a link to an OPML file as well? This way feed readers like Inoreader that support [OPML subscription](https://blog.inoreader.com/2014/05/opml-subscriptions.html) would be able to auto update themselves when new feeds/friends are added to the list?

Depending on your infrastructure, you could potentially leverage the old [Link Manager](https://codex.wordpress.org/Links_Manager) within WordPress which provided OPML outputs as well as [outputs arranged by category](https://boffosocko.com/2017/11/13/opml-files-for-categories-within-wordpresss-links-manager/#OPML%20files%20by%20category). This would prevent you from needing to rebuild the side-files unless you’re doing that already.

(Originally published at: https://boffosocko.com/2018/06/11/reply-to-allow-reading-friends-feeds-in-a-feed-reader/)

**Comment by akirk** [comment]
I don't see how this to be different from providing a download link. After all it's just a URL, just now it's protected through WordPress wp-admin authentication. I guess it's viable to add another means of authentication for that URL (for example an auth URL parameter).

I personally don't (yet) see the need for it but feel free to submit a patch!
