### ISSUE TITLE
Public Friends page seems broken in 2.3.0

### ISSUE THREAD

**Issue by regenpfeifer** [akirk/friends#187]
After updating to v 2.3.0 the public friends page (/friends/?public) seems broken. Although I have several friends-feeds, the public page shows me none of them, only the standard text of this page (Hallo Freund! Kennst du einen meiner Freunde? Vielleicht willst du ihnen auch eine Freundschaftsanfrage senden?) The previous version showed me all of my friends feeds, without the editing functions of the private page.

**Comment by regenpfeifer** [comment]
I've tried to deactivate all other plugins, cleared the browser cache, switched the theme etc. - nothing worked. I still don't see any friends' feed, but only the standard text of the page.

![grafik](https://user-images.githubusercontent.com/1929807/216726311-4a4a1569-6f92-4a1e-b522-e354e936b713.png)

**Comment by lordmatt** [comment]
/friends/?public gives me a 404.

**Comment by jeffpaul** [comment]
Noting that on WordPress 6.7.1 and Friends 3.1.9 the /friends/?public link does not 404 for me, so perhaps this is now resolved and can be closed?

**Comment by regenpfeifer** [comment]
I'm not using the plugin at the moment; so, unfortunately, I can't tell.

**Comment by jeffpaul** [comment]
@akirk probably fine to close this issue then?
