### ISSUE TITLE
Error on incoming ActivityPub comment

### ISSUE THREAD

**Issue by wiwie** [akirk/friends#190]
When sending a comment/reply from misskey.de (ActivityPub) to a local blog post federated via ActivityPub, the comment is never received and in the logs I find the following error:

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'guid IN ('XXX', 'XXX' at line 1 for query SELECT ID from wp_posts WHERE post_type IN ( 'friend_post_cache' ) AND post_author = 6AND guid IN ('X', 'XXX') LIMIT 1 made by require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array('parse_request'), WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WP_REST_Server->respond_to_request, Activitypub\\Rest\\Inbox::user_inbox_post, do_action('activitypub_inbox'), WP_Hook->do_action, WP_Hook->apply_filters, Friends\\Feed_Parser_ActivityPub->handle_received_activity, Friends\\Feed->process_incoming_feed_items, Friends\\Feed->url_to_postid

I believe the reason is here in this line:
https://github.com/akirk/friends/blob/ffe9030b18a796cce37a1899078511fd45b56273/includes/class-feed.php#L1119
the line
`$sql .= 'AND guid IN (%s, %s) LIMIT 1';`
should read
`$sql .= ' AND guid IN (%s, %s) LIMIT 1';`
instead.

As a result, the SQL query is missing a space between "AND" and whatever comes before.

I can send a PR if this is wanted.

**Comment by akirk** [comment]
Indeed that must be the problem, sorry about that bug! Would appreciate a PR indeed so that you can get credit! Thanks!
