### ISSUE TITLE
Bookmarklet or Extension to subscribe to a site

### ISSUE THREAD

**Issue by akirk** [akirk/friends#21]

**Comment by akirk** [comment]
Added a bookmarklet in 0.13.

**Comment by HammyHavoc** [comment]
Would love to see a plugin for Chromium-based browsers. I recently dropped Mozilla Firefox.

**Comment by akirk** [comment]
The extension also works in Chrome: https://github.com/akirk/friends-browser-extension

**Comment by akirk** [comment]
And the bookmarklet works in any browser that can do bookmarklets.

**Comment by akirk** [comment]
> The extension also works in Chrome

Oh I suppose I need to submit it to the Chrome store.

**Comment by HammyHavoc** [comment]
> > The extension also works in Chrome
> 
> Oh I suppose I need to submit it to the Chrome store.

Even better! That way the extension being installed will sync between Chromium-based browsers, even non-Google-owned browsers.
