### ISSUE TITLE
Nickname Conflicts

### ISSUE THREAD

**Issue by huckabarry** [akirk/friends#212]
Yesterday I tried to update my public facing administrator profile and noticed that it wouldn't allow me to modify my website url. It was throwing an error that my nickname was already being used by someone else. Turns out one of the people I subscribed to has the same nick as me. I had to delete that user in order to update my own profile.

**Comment by akirk** [comment]
Thanks for your report! Since [2.6.0](https://github.com/akirk/friends/releases/tag/2.6.0), just subscribing to someone will not create local user #215. Thus, I'd categorize this one as resolved for now.
