### ISSUE TITLE
Refresh Widget does not prepend home URL to /friends/?refresh link

### ISSUE THREAD

**Issue by heathenstorm** [akirk/friends#213]
The refresh widget has a hardcoded /friends/?refresh link, which fails if the Wordpress site is located in a subdirectory.

This should be amended to use the home_url function.

**Comment by akirk** [comment]
Thanks for reporting this, it has been fixed in the [latest 2.6.0 release](https://github.com/akirk/friends/releases/tag/2.6.0).
