### ISSUE TITLE
[Activitypub] Videos in posts don't federate

### ISSUE THREAD

**Issue by aadilayub** [akirk/friends#216]
I noticed video attachments aren't showing up for posts in the fediverse. 

For example, here's how [this post](https://sunbeam.city/@murilove/110405170665454489) appears in my friends feed (and on mastodon apps):

![image](https://github.com/akirk/friends/assets/31581044/fd6c575d-34c8-472c-82d0-d6c1f65351a7)

and here's the actual post:

![image](https://github.com/akirk/friends/assets/31581044/83d9925b-8b5c-44f5-b833-f5d6413d21c6)

**Comment by aadilayub** [comment]
Here's another example:

![image](https://github.com/akirk/friends/assets/31581044/ca17fe70-88a8-4592-8dd3-6e782c411646)

The [actual post](https://merveilles.town/@aadil/108923843936544263):

![image](https://github.com/akirk/friends/assets/31581044/90295349-6915-4b4c-978c-1f014c0c8fde)

**Comment by akirk** [comment]
Thanks for reporting this, it has been fixed in the [latest 2.6.0 release](https://github.com/akirk/friends/releases/tag/2.6.0).
