### ISSUE TITLE
/friends/type/status/ only shows my own posts

### ISSUE THREAD

**Issue by lordmatt** [akirk/friends#228]
I have run into a problem that while it says there are 60+ updates to see /friends/type/status/ shows only my own.

This is a fresh install running only IndieWeb plugins,  ActivityPub, and friends. The theme is SemPress.

**Comment by lordmatt** [comment]
I switched to another theme which seemed to fix it.

**Comment by lordmatt** [comment]
I think this can be closed now

**Comment by akirk** [comment]
Thanks for checking back!
