### ISSUE TITLE
Set custom content type for reblogs

### ISSUE THREAD

**Issue by eiland-asbl** [akirk/friends#276]
I'm tooting from my blog using a custom content type, and I would like the reblogs to be posted as this type as well, not as a regular news post. Hoe could I set this up?

**Comment by akirk** [comment]
Oh, I didn't consider that. [Right now it's hardcoded](https://github.com/akirk/friends/blob/ae41c495d3eaece08fb6130b50cbf60807b81624/includes/class-frontend.php#L355) but I can add a filter if that's enough for you?

**Comment by eiland-asbl** [comment]
Where would the filter be? In the friends settings? Or do you need to choose it at every toot? But it sounds good to me, thanks for the quick follow up!!

**Comment by akirk** [comment]
A filter would be only in code but I could also add a setting in the UI.

**Comment by eiland-asbl** [comment]
As its dealing with custom post types, which you need to set up in functons.php anyway, code would be fine I guess?

**Comment by akirk** [comment]
@eiland-asbl This will be in the next version, here is the docs: https://github.com/akirk/friends/wiki/friends_reblog_pre_insert_post

**Comment by eiland-asbl** [comment]
oh, same goes for replies!!
