### ISSUE TITLE
Friends posts dont show

### ISSUE THREAD

**Issue by eiland-asbl** [akirk/friends#280]
My blog is located at domain.com, but wordpress itself is residing in domain.com/wp/

Somehow i have the feeling this causes some problems for the friends plugin?

For example, i have subscriptions, which indicate to have posts, but when I select the account, it displays 

![image](https://github.com/akirk/friends/assets/5505151/f024d478-b931-432d-8fdf-4839dfd77407)

Also in the admin nav bar the links to admin pages lack the /wp/ in the url, leading tot 404s  (thats why i think that maybe these issues are related?)
![image](https://github.com/akirk/friends/assets/5505151/342f77d4-ee86-438f-900a-314e3ef84d35)

**Comment by akirk** [comment]
I'm sorry, I personally don't run any subdirectory install which is why in some areas this seems to come out wrong. The WordPress way to do the latter is to use `home_url()` but the former might be neglegance on my behalf with parsing the URL to determine the author slug.

I guess, I'll best create a subdirectory install to test it and fix it. Thanks for pointing this out!

**Comment by eiland-asbl** [comment]
I figured :D

**Comment by akirk** [comment]
I now finally tested in a subdir install and as you already hinted at, it works there equally well. So there is something specific to your WordPress install, likey a plugin interference. Do you maybe have the Post Kinds plugin installed?

**Comment by akirk** [comment]
@eiland-asbl did you find the cause in the end or is it still a problem? If not, I'd suggest to close this issue for now.

**Comment by eiland-asbl** [comment]
unfortunately still unresolved :/

**Comment by eiland-asbl** [comment]
Remarkable, I finaly got around to switching off plugins and themes, I have two instances with the same issue, one using a twenty fifteen child theme and one using a twenty twelve child theme. Both instances work fine with their clean parent theme, but enabling their children muffles friends, meaing per user post are not being shown....

**Comment by eiland-asbl** [comment]
didnt mean to close

**Comment by eiland-asbl** [comment]
Narrowed it down to [this](https://wordpress.stackexchange.com/a/270557) custom post-snippet in functions.php somehow interfering with friends, resulting in hiding all posts from the friends dashboard.

Any idea what is going on?

**Comment by eiland-asbl** [comment]
replaced it with [this](https://wordpress.stackexchange.com/a/173158) snippet, now it works.

It seems that the (any) post type which the friends plugin is using, was replaced with my custom post type in the list of types to display as soon as an author page was shown.  now it just adds my custom post type to aforesaid list, leaving the author toots visible.
