### ISSUE TITLE
Hide @mentions setting on Edit User page doesn't work

### ISSUE THREAD

**Issue by mikewmerritt** [akirk/friends#283]
I've noticed this setting on Edit User (edit-friend) doesn't work. I thought it's possible it's extraneous since the identical setting on Edit Feeds (edit-friend-feeds) does work.

Looking further, I see the activitypub_save_settings() function in class-feed-parser-activitypub.php and do_action callback friends_edit_friend_after_form_submit within process_admin_edit_friend_feeds() in class-admin.php seem to be expecting the setting to be part of the Edit Feeds page.

**Comment by akirk** [comment]
Thank you! This will be fixed in Friends 2.8.5.
