### ISSUE TITLE
Boost arbitrary toots

### ISSUE THREAD

**Issue by eiland-asbl** [akirk/friends#284]
I would like to be able to boost arbitrary toots, so from accounts I don't (yet) follow).
So for example, I don't follow Matt, but  see [this](https://mastodon.social/@photomatt/111835384072606200) toot and want to boost it with my wordpress. No i can only subscribe to an account but then i have no option of importing the toot and boost it...

**Comment by akirk** [comment]
Thank you for the suggestion! This will land in Friends 2.8.5.

**Comment by akirk** [comment]
Indeed, the boost currently only goes directly out to your followers. I realize that this doesn't conform to this setting:

<img width="656" alt="Screenshot 2024-02-08 at 09 21 14" src="https://github.com/akirk/friends/assets/203408/837df339-e13c-474d-817f-1df5e4ba74eb">

So in the next iteration, it will also generate a blog post (post format: status) when you boost it. Maybe I can also put the textbox there. While on AcitvityPub (currently) you cannot send a message along with the boost, it could be in the blog post.
