### ISSUE TITLE
Bug: “Friend Requests” email notification checkbox does not update on Settings -> Notifications

### ISSUE THREAD

**Issue by kgourlay** [akirk/friends#311]
The checkbox for “Friend Requests” appears to always be blank, does not change when “Save Changes” is clicked.  Fix by adding missing code to includes/class-admin in the `process_admin_notification_manager()` function:

```
		if ( isset( $_POST['friend_request_notification'] ) && $_POST['friend_request_notification'] ) {
			delete_user_option( get_current_user_id(), 'friends_no_friend_request_notification' );
		} else {
			update_user_option( get_current_user_id(), 'friends_no_friend_request_notification', 1 );
		}
```

**Comment by cmdr-nova** [comment]
Chiming in that this bug is quite disheartening as I'd like to follow people back via my blog, but can't risk killing my daily SendGrid limits.
