### ISSUE TITLE
On multisite, the admin menu "My Friends feed" links to main hostname, not the current one

### ISSUE THREAD

**Issue by zjuul** [akirk/friends#340]
Using a multisite with domain mapping.

Main domain: main.com
Subsite: sub.com

When on the dashboard on sub.com, the first link in the admin panel links to **main.com/friends** in stead of **sub.com/friends**

![image](https://github.com/user-attachments/assets/d82401f6-f2dd-4929-adfa-9bbe5dd55d50)

The other 2 links (_add <blogname> as friend_> and _<blogname>'s Profile_) are pointing to the correct domain

**Comment by akirk** [comment]
This should be ok since version 2.9.5.
