### ISSUE TITLE
Capability checks (missing or failing) for subscribers

### ISSUE THREAD

**Issue by carstingaxion** [akirk/friends#367]
Hello Alex,

we are running your plugin on gatherpress.org, where I saw some errors after clicking in the Admin Bar or on the Dashboard Widget the links to "Add a new friend". 

I'm logged into the website as a subscriber and I guess, I shouldn't see those links at all. 
I made a short video of what I mean.

https://github.com/user-attachments/assets/b8a60f12-5b9d-4534-bc41-002ebb94c83a

**Comment by akirk** [comment]
You are right, a subscriber shouldn't see the widget. Will be fixed in #368. Danke!

**Comment by carstingaxion** [comment]
Wow, That was fast.

Cool, you fixed it & gern geschehen!
