### ISSUE TITLE
Subscribing to a Threads user via ActivityPub isn't supported

### ISSUE THREAD

**Issue by 2br-2b** [akirk/friends#376]
Hello!

Right now, if I try to subscribe to a federated Threads user via ActivityPub (see `@alex.stamos@threads.net` as an example), it provides an error that there aren't any feeds available:
![image](https://github.com/user-attachments/assets/2fc239c6-ef67-40f9-883b-8e8b9b1a7f46)

![image](https://github.com/user-attachments/assets/2b75c4d1-04b5-424e-9001-9fd7d3ee69f7)

**Comment by akirk** [comment]
Thanks for the report. I need to investigate what's going on. The request below typically works for Mastodon servers but looks like not for Threads.

https://webfinger.net/lookup/?resource=alex.stamos%40threads.net

```
$ curl -H"Accept: application/activity+json" https://threads.net/ap/users/17841400831593087/
{"success":false,"error":"Not found"}                                                                                                                                             
```

@pfefferle do you have an idea here?

**Comment by akirk** [comment]
Oh, I recall that on threads.net you need to enable ActivityPub for your account. So [Alex Stamos](https://www.threads.net/@alex.stamos) didn't do this.

![image](https://about.fb.com/wp-content/uploads/2023/07/01_Turn-on-Fediverse-Sharing.jpg?w=1920)

**Comment by akirk** [comment]
Oh sorry, you said they were federated and I can confirm this on a Mastodon account, so I need to find a way to talk to threads.net differently.

![Screenshot 2024-10-18 at 09 13 12](https://github.com/user-attachments/assets/bd7e871e-a5a7-40fc-a912-9fb0e6198059)

**Comment by akirk** [comment]
I just released 3.1.2 which should fix this.

**Comment by 2br-2b** [comment]
Thank you so much! However, the feeds are returning as empty:

![Screenshot_20241018-130142.png](https://github.com/user-attachments/assets/147ae13b-5c99-4b64-993e-afde5835bd0b)

**Comment by akirk** [comment]
Fetching the "feed" is fetching the "outbox" in ActivityPub. I think I read that threads.net doesn't support it but I need to confirm it. You should receive new items via push, though but it looks like Alex Stamos hasn't posted anything in a while.
