### ISSUE TITLE
How to  do a complete uninstall

### ISSUE THREAD

**Issue by stefangilgen** [akirk/friends#414]
How can the plugin be completely uninstalled without leaving subscriptions or other "leftovers"?

**Comment by akirk** [comment]
There is an [uninstall routine already](https://developer.wordpress.org/reference/functions/register_uninstall_hook/) but it forgot to delete "subscription users." In case it fails, you can also use something like WP Sweep that will delete terms that belong to unregistered taxonomies (which we [declare as being used while the Friends plugin is activated](https://github.com/akirk/friends/blob/main/includes/class-third-parties.php#L58-L69)).

This routine kicks in when you click "Delete" in the plugins screen:
![Screenshot 2024-12-15 at 10 36 41](https://github.com/user-attachments/assets/ba20f4d2-2106-4561-9857-daffd9b84f91)

So until #415 is released through a new version, the subscriptions will remain. Sorry about that.

**Comment by stefangilgen** [comment]
o.k. thanks. I was just checking for a future talk, where I will mention the plugin, but would make sure, people may be able to uninstall after testing.

**Comment by stefangilgen** [comment]
According to the counter, the subscriptions are gone after a deinstall.
![CleanShot 2024-12-26 at 15 23 38@2x](https://github.com/user-attachments/assets/7c59ee14-8d21-4453-84b4-7d45279ffa1b)


But in real life, the contributions are still there.

![CleanShot 2024-12-26 at 15 23 45@2x](https://github.com/user-attachments/assets/c14c4567-5807-4466-a671-12d45fc6a791)

How do you get rid of them? WP-Sweep doesn't help either.
