### ISSUE TITLE
Hide dashboard notification

### ISSUE THREAD

**Issue by pfefferle** [akirk/friends#47]
The dashboard notification seems to stay until sent your first friend request, but it would be nice to have an option to disable it.

**Comment by akirk** [comment]
I agree, this is meant for discoverability, I'll add a Dismiss link that will disable it permantently.

For posterity, this is about this message:
<img width="1260" alt="Screenshot 2020-11-25 at 13 29 51" src="https://user-images.githubusercontent.com/203408/100228081-6c760700-2f22-11eb-8e78-fbb91864900c.png">
