### ISSUE TITLE
Question: Is there a function to get the followers count?

### ISSUE THREAD

**Issue by pfefferle** [akirk/friends#48]
I want to add the friends follower to my profile page (Autonomie Theme): https://notiz.blog/author/matthias-pfefferle/

**Comment by akirk** [comment]
At the moment there is only a shortcode `[friends-count]`, it will return the number of users with the role "Friend".

<img width="595" alt="Screenshot 2020-11-13 at 13 56 36" src="https://user-images.githubusercontent.com/203408/99074471-16b36d80-25b8-11eb-8bbc-cb3c980241d8.png">
