### ISSUE TITLE
"Antworten" link/text in ActivityPub representation

### ISSUE THREAD

**Issue by pfefferle** [akirk/friends#56]
If I enable the friends plugin, I see an "Antworten" link/text in the ActivityPub JSON, for example: https://notiz.blog/2020/12/23/chrssmas/activitypub/

This will sadly also be pushed to other ActivityPub servers.

**Comment by akirk** [comment]
Sorry about that, I have removed this particular function (Reactions) from the plugin, it might come back as a plugin for the Friends plugin. But for now this should solve your problem.
