### ISSUE TITLE
Public "Search" shows items from friends

### ISSUE THREAD

**Issue by pfefferle** [akirk/friends#66]
The public search request also shows results from the feeds of my "friends": https://notiz.blog/?s=indieweb

**Comment by akirk** [comment]
So far I have been unable to reproduce this. I understand you have deleted the respective user that accidentally had posts caused by #67 but does it happen for other friend users?

**Comment by akirk** [comment]
This was fixed for good with 41a30ef27263b47a3469836778fd842fdcd61cdc which ensures that the wp_query is only modifed on the friends page.
