### ISSUE TITLE
The "More Details" links do not work on the Friends plugins area

### ISSUE THREAD

**Issue by meszarosrob** [akirk/friends#73]
When clicking on the "More details" at `wp-admin/admin.php?page=friends-plugins` nothing happens.

![image](https://user-images.githubusercontent.com/6097856/117030955-cddba680-ad08-11eb-9b68-1e95599b0839.png)

There's a click event added for all elements that have the `button` class here

https://github.com/akirk/friends/blob/527e8ea2265005defa16ab54e61c0218638832a3/plugin-installer.js#L126-L152

and that seems to be the cause of the issue.

**Comment by meszarosrob** [comment]
A solution would be to add a specific class to the link, maybe `details`

https://github.com/akirk/friends/blob/527e8ea2265005defa16ab54e61c0218638832a3/templates/admin/plugin-info.php#L33

and then modifying the JS selector to `.friends-plugin-installer a.button:not(.detail)` 

---

The `thickbox` class gives me the impression that there was the intention to have a plugin details preview link on the default plugin screen, but maybe those can be removed since that is not implemented.

**Comment by akirk** [comment]
Closed via #74
