### ISSUE TITLE
`friends_main_feed_header` action fired without any data

### ISSUE THREAD

**Issue by meszarosrob** [akirk/friends#75]
> Notice: Undefined index: friend_user in friends/templates/frontend/main-feed-header.php on line 63

Here the action `friends_main_feed_header` is fired:

https://github.com/akirk/friends/blob/527e8ea2265005defa16ab54e61c0218638832a3/templates/frontend/main-feed-header.php#L63

but sometimes the `friend_user` is undefined. This only happens on the main feed, not when you are viewing a particular feed/subscription.

The issue seems to come from here:

https://github.com/akirk/friends/blob/527e8ea2265005defa16ab54e61c0218638832a3/templates/frontend/header.php#L40-L57

in the `else` nothing is passed.

**Comment by meszarosrob** [comment]
Not sure what would be the best approach here: pass a `null` to the action, maybe a null object, fire different actions based on the view? Or maybe don't pass any data if the friend can be inferred in other ways.

The action is not used in the plugin, but did not check in the add-ons.

**Comment by akirk** [comment]
Nice catch, thank you. This was likely a copy and paste error from the author header template part. The point of the main feed is to not have a user selected, so there is no point in trying to pass it as an argument.
