### ISSUE TITLE
Has issue with Peepso plugin

### ISSUE THREAD

**Issue by smileybrian** [akirk/friends#88]
This might not be worth exploring a resolution as I can think of no condition where a site would use both plugins. I was surprised a search came up empty as I was sure people who explore Friends would also explore Peepso as they both seek to create community. 

The specific issue is that with Friends enabled the menu for Peepso disappears. 

Thanks for your efforts.

**Comment by akirk** [comment]
Thank you for the report! I found the problem and this will be fixed in the next version!
